config/routes.rb
Rails.application.routes.draw do
  root 'blog_post#index'
  get 'posts' => 'blog_post#index', as: 'blog_posts'
  get 'posts/new' => 'blog_post#new', as: 'new_blog_post'
  get 'posts/:id' => 'blog_post#show', as: 'blog_post'
  post 'posts' => 'blog_post#create'
  get 'posts/edit/:id' => 'blog_post#edit', as: 'edit_blog_post'
  patch 'posts/:id' => 'blog_post#update'
  delete 'posts/:id' => 'blog_post#destroy', as: 'delete_blog_post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_post_controller.rb
class BlogPostController < ApplicationController
    def home
    end
    def index
        @posts = BlogPost.all
    end
    def show
        @post = BlogPost.find(params[:id])
    end
    def new
        @post = BlogPost.new
    end    
    def create
        @post = BlogPost.create(blog_params)
        if @post.valid?
            redirect_to blog_posts_path
        else
            redirect_to new_blog_post
        end
    end

    def edit
        @post = BlogPost.find(params[:id])
    end

    def update
        @post = BlogPost.find(params[:id])
         @post.update(blog_params)
        if @post.valid?
            redirect_to blog_post_path(@post)
        else
            redirect_to edit_blog_post_path(@post)
        end
    end

    def destroy
        @post = BlogPost.find(params[:id])
        if @post.destroy
            redirect_to blog_posts_path
        end
    end

    private
    def blog_params
        params.require(:blog_post).permit(:name, :text)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_post_helper.rb
module BlogPostHelper
end

app/views/blog_post/edit.html.erb
<h2>Edit Post</h2>
<%= form_with model: @post do |form| %>

    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :text %>
    <%= form.text_field :text %>

    <br>
    <br>

    <%= form.submit 'Edit Post' %>
    <% end %>

<br>
    <h4><%= link_to 'Back To All Posts', posts_path %></h4>

app/views/blog_post/index.html.erb
<h1>All The Posts</h1>
<% @posts.map do |value|%>
    <ul>
        <li>
            <%= link_to value.name, blog_post_path(value) %>
        </li>
    </ul>
<% end %>

<%= link_to 'Add a New Post', new_blog_post_path %>

app/views/blog_post/new.html.erb
<h2>Add a new post<h2>
<%= form_with model: @posts, local: true do |form| %>

    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :text %>
    <%= form.text_field :text %>

    <br>

    <%= form.submit 'Create Post' %>
    <% end %>

    <br>

    <h4><%= link_to 'Back To All Posts', posts_path %></h4>

app/views/blog_post/show.html.erb
<h2><%= @post.name %></h2>

<%= @post.text %>

<br>
<br>
<%= link_to 'Edit Post', edit_blog_post_path(@post) %>
<br>
<br>

<%= button_to 'Delete Post', delete_blog_post_path(@post), method: :delete, form:{data: { 'turbo-confirm': 'Are you sure?'} }%>
<br>
<%= link_to 'Back To All Posts', blog_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>